apiVersion: apps/v1
kind: Deployment
metadata:
  name: city-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: city-app
  template:
    metadata:
      labels:
        app: city-app
    spec:
      containers:
        - name: app
          image: "{{ .Values.image }}:{{ .Values.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: ES_HOST
              value: "http://elasticsearch:9200"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:7.17.21
          env:
            - name: discovery.type
              value: single-node
            {{- if .Values.elasticsearch.esJavaOpts }}
            - name: ES_JAVA_OPTS
              value: {{ .Values.elasticsearch.esJavaOpts | quote }}
            {{- end }}
          ports:
            - containerPort: 9200
          {{- with .Values.elasticsearch.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}

